### ISSUE TITLE
[BUG] wallet in owner_api mode is crashing. 

### ISSUE THREAD

**Issue by johanneshahn** [EpicCash/epic-wallet#29]
CLI Wallet panics in owner_api mode at unknown states.
2022-05-09 02:16:01.429 ERROR
thread 'unnamed' panicked at 'failed to set up alternative stack guard page: Cannot allocate memory (os error 12)': library/std/src/sys/unix/stack_overflow.rs:159   0: epic_util::logger::send_panic_to_log::{{closure}}
   1: std::panicking::rust_panic_with_hook
             at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/std/src/panicking.rs:628:17
   2: std::panicking::begin_panic_handler::{{closure}}
             at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/std/src/panicking.rs:521:13
   3: std::sys_common::backtrace::__rust_end_short_backtrace
             at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/std/src/sys_common/backtrace.rs:141:18
   4: rust_begin_unwind
             at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/std/src/panicking.rs:517:5
   5: std::panicking::begin_panic_fmt
             at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/std/src/panicking.rs:460:5
   6: std::sys::unix::stack_overflow::imp::get_stackp
             at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/std/src/sys/unix/stack_overflow.rs:159:13
      std::sys::unix::stack_overflow::imp::get_stack
             at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/std/src/sys/unix/stack_overflow.rs:165:32
      std::sys::unix::stack_overflow::imp::make_handler
             at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/std/src/sys/unix/stack_overflow.rs:176:21
   7: std::sys::unix::stack_overflow::Handler::new
             at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/std/src/sys/unix/stack_overflow.rs:14:9
      std::sys::unix::thread::Thread::new::thread_start
             at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/std/src/sys/unix/thread.rs:104:32
   8: start_thread
   9: clone

**To Reproduce**
cannot reproduce. does happen sometimes. The Wallet is running in owner_api mode for days
and suddenly crashing.

**Required data**
 - ./epic-wallet owner_api
 - OS: Ubuntu-1910-eoan-64-minimal
 - Rust Version stable

**Comment by johanneshahn** [comment]
Error does not happen again.
